version: 0.0
os: linux
files:
  - source: /mm.war
    destination: /var/lib/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: stop_application
      timeout: 300
  BeforeInstall:
    - location: install_dependencies
      timeout: 300
  ApplicationStart:
    - location: start_application
      timeout: 300
  ValidateService:
    - location: basic_health_check.sh
