version: 0.0
os: linux
files:
  - source: /mm.war
    destination: /var/lib/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: deploy/stop_application
      timeout: 300
  BeforeInstall:
    - location: deploy/install_dependencies
      timeout: 300
  ApplicationStart:
    - location: deploy/start_application
      timeout: 300
  ValidateService:
    - location: deploy/basic_health_check.sh
